#!/usr/bin/python3

from sys import argv


def factorize(n):
    for i in range(2, n):
        if n % i == 0:
            return i
    return None


def main():
    if len(argv) != 2:
        print("Usage: factors <file>")
        return

    with open(argv[1]) as fi:
        for line in fi:
            n = int(line)
            first = factorize(n)
            print("{}={}*{}".format(n, first, n // first))


if __name__ == "__main__":
    main()
