#!/usr/bin/python3

import sys


def factorize(n):
    """"factorize integers greater than 1"""
    for i in range(2, n):
        if n % i == 0:
            return (i, n // i)
    return None


def main():
    """"print factors"""
    if len(sys.argv) != 2:
        print("Usage: factors <file>")
        return
    try:
        with open(sys.argv[1], "r") as fi:
            for line in fi:
                n = int(line.strip())
                factors = factorize(n)
                if factors is not None:
                    print("{:.0f}={:.0f}*{:.0f}".format(n, factors[1], factors[0]))
    except:
        pass

if __name__ == "__main__":
    main()
