#!/usr/bin/python3

import sys


def factorize(n):
    for i in range(2, n):
        if n % i == 0:
            return (i, n // i)
    return None


def main():
    if len(sys.argv) != 2:
        print("Usage: factors <file>")
        return

    with open(sys.argv[1], "r") as fi:
        for line in fi:
            n = int(line.strip())
            factors = factorize(n)
            if factors is not None:
                print(f"{n}={factors[1]}*{factors[0]}")


if __name__ == "__main__":
    main()
