#!/usr/bin/python3

import sys
import math


def is_prime(n):
    if n < 2:
        return False
    for i in range(2, int(math.sqrt(n)) + 1):
        if n % i == 0:
            return False
    return True


def factorize(n):
    for i in range(2, n):
        if n % i == 0 and is_prime(i) and is_prime(n // i):
            return (i, n // i)
    return None


def main():
    if len(sys.argv) != 2:
        print("Usage: rsa <file>")
        return

    with open(sys.argv[1], "r") as f:
        for line in f:
            n = int(line.strip())
            factors = factorize(n)
            if factors is not None:
                print(f"{n}={factors[0]}*{factors[1]}")


if __name__ == "__main__":
    main()
